# Generated by Django 5.2.10 on 2026-03-13 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
