# Generated by Django 5.2.10 on 2026-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('alluri_sitharama_raju', 'Alluri Sitharama Raju'), ('anakapalli', 'Anakapalli'), ('ananthapuramu', 'Ananthapuramu'), ('annamayya', 'Annamayya'), ('bapatla', 'Bapatla'), ('chittoor', 'Chittoor'), ('east_godavari', 'East Godavari'), ('eluru', 'Eluru'), ('guntur', 'Guntur'), ('kakinada', 'Kakinada'), ('konaseema', 'Konaseema'), ('krishna', 'Krishna'), ('kurnool', 'Kurnool'), ('nandyal', 'Nandyal'), ('ntr', 'NTR'), ('palnadu', 'Palnadu'), ('parvathipuram_manyam', 'Parvathipuram Manyam'), ('prakasam', 'Prakasam'), ('srikakulam', 'Srikakulam'), ('spsr_nellore', 'Sri Potti Sriramulu Nellore'), ('sri_sathya_sai', 'Sri Sathya Sai'), ('tirupati', 'Tirupati'), ('visakhapatnam', 'Visakhapatnam'), ('vizianagaram', 'Vizianagaram'), ('west_godavari', 'West Godavari'), ('ysr_kadapa', 'YSR Kadapa'), ('other', 'Other')], default='Anantapur', max_length=50),
        ),
    ]
